services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    container_name: gctu-attendance-app

    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
