from enum import Enum


class SimpleExceptionType(Enum):
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    FAILED = "FAILED"
    INVALID_TOKEN_PROVIDED = "INVALID_TOKEN_PROVIDED"
    WRONG_PASSWORD = "WRONG_PASSWORD"
    NOT_FOUND = "NOT_FOUND"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    INVALID_ACCOUNT = "INVALID_ACCOUNT"
    USER_AGENT_NOT_PROVIDED = "USER_AGENT_NOT_PROVIDED"
    OUTDATED_USER_AGENT = "OUTDATED_USER_AGENT"
    NOT_SPECIFIED = "NOT_SPECIFIED"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"